name: Animals Island

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch'
        required: true
        default: 'main'
      slack-bot-token:
        type: string
        description: 'Slack bot token'
      channel-id:
        type: string
        description: 'Slack channel id'
      # version:
      #   type: string
      #   description: 'Version'
      #   required: true
      #   default: '0.1.0'
                
jobs:
  testflight:
    runs-on:
      - self-hosted
      - macOS
    environment: animals-island
    steps:
      - name: Notify started
        if: ${{ inputs.slack-bot-token != '' && inputs.channel-id != '' }}
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.channel-id }}
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            Xcode
      - name: Checkout
        run: |
          git clone -b ${{ inputs.branch }} codecommit::ap-northeast-2://Animal_Island Repository
          cd Repository
          sed -i '' 's/https:\/\/git-codecommit.ap-northeast-2.amazonaws.com\/v1\/repos\//codecommit::ap-northeast-2:\/\//g' .gitmodules
          git submodule init
          git submodule update
      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv Repository/The_Maldives/* .
          rm -rf Repository
          ls -lah
      - uses: maxnowack/local-cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-animalsisland-ios
      - name: Export Xcode project
        uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: None
          # version: ${{ inputs.version }}
          targetPlatform: iOS
          skipActivation: true
      - name: Build and upload testflight
        env:
          APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          ITC_TEAM_ID: ${{ vars.ITC_TEAM_ID }}
          TEAM_ID: ${{ vars.TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_USER: ${{ vars.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: Xcode/init.sh "build/iOS/iOS" "run.sh"
      - name: Notify finished
        if: ${{ inputs.slack-bot-token != '' && inputs.channel-id != '' }}
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.channel-id }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
      - name: Notify if failed
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.channel-id }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Failed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "FF2C98",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
