name: Animals Island

on:
  workflow_dispatch: 
    inputs:
      branch:
        type: string
        description: 'Branch'
        required: true

jobs:
  testflight:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - run: echo "Welcome to Animals Island!"
      - run: echo "Repository is ${{ inputs.repo }}"
      - run: echo "Branch or tag is ${{ inputs.ref }}"
      - name: Checkout
        run: git clone -b ${{ inputs.branch }} ${{ secrets.ANIMALS_REPO_URL }} Repository && cd Repository && \
          git submodule init && \
          git submodule update
