name: Animals Island

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Ref'
        required: true
        default: 'origin/HEAD'
      # version:
      #   type: string
      #   description: 'Version'
      #   required: true
      #   default: '0.1.0'
                
jobs:
  testflight:
    runs-on:
      - self-hosted
      - macOS
    environment: animals-island
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            Xcode
      - name: Checkout
        run: |
          git clone codecommit::ap-northeast-2://Animal_Island Repository
          cd Repository
          git checkout ${{ inputs.ref }}
          sed -i '' 's/https:\/\/git-codecommit.ap-northeast-2.amazonaws.com\/v1\/repos\//codecommit::ap-northeast-2:\/\//g' .gitmodules
          git submodule init
          git submodule update
      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv Repository/The_Maldives/* .
          rm -rf Repository
          ls -lah
      - uses: maxnowack/local-cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-animalsisland-ios
      - name: Export Xcode project
        uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: None
          # version: ${{ inputs.version }}
          targetPlatform: iOS
          skipActivation: true
      - name: Build and upload testflight
        env:
          APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          ITC_TEAM_ID: ${{ vars.ITC_TEAM_ID }}
          TEAM_ID: ${{ vars.TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: Xcode/init.sh "build/iOS" "run.sh"
