name: Animals Island

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Branch'
        required: true
        default: 'HEAD'
jobs:
  testflight:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Checkout
        run: |
          git clone -b ${{ inputs.branch }} codecommit::ap-northeast-2://Animal_Island Repository && cd Repository && \
          git submodule init && git submodule update
