name: External

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      ref:
        required: true
        default: main
          
jobs:
  run:
    runs-on: 
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          token: ${{ env.PAT_AARON }}
