name: External

on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: 'empty'
          
jobs:
  run:
    runs-on: 
      - self-hosted
      - macOS
    steps:
      - run: echo "run ${{ inputs.message }}"
