name: Get job id

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running job1"
      - name: Using action
        id: get-job-id
        uses: TinycellCorp/Actions/.github/actions/get-job-id@main
        with:
          name: job1
          token: ${{ github.token }}
      - name: echo job1 id
        run: echo "${{ steps.get-job-id.outputs.id }}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: request jobs
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/runs/$RUN_ID/jobs \
          --jq '.jobs[] | select(.name == "job1") | .id'
        
          
