name: Get job id

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running job1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: request jobs
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/runs/$RUN_ID/jobs \
          --jq '.jobs[] | select(.name == "build") | .id'
        
          
