name: iOS

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: TinycellCorp/Actions/.github/actions/checkout@main
      - uses: TinycellCorp/Actions/.github/actions/setup-unity@main
      - uses: siren403/unity-builder@add-install-unity-modules
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
