name: Logs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest
    steps:
      - run: echo "run job1"
  job2:
    runs-on:
      - ubuntu-latest
    needs:
      - job1
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/runs/$RUN_ID/jobs
