name: Logs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest
    steps:
      - run: echo "run job1"
  job2:
    runs-on:
      - ubuntu-latest
    needs:
      - job1
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/runs/$RUN_ID/jobs
      - id: job1-id
        uses: ayachensiyuan/get-action-job-id@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: 'job1'
      - env:
          JOB_ID: ${{ steps.job1-id.outputs.jobId }}
        run: |
          response=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/jobs/$JOB_ID/logs)

          echo "$response"
