name: Matrix

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - self-hosted
      - macOS
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
          - Android
    steps:
      - uses: TinycellCorp/Actions/.github/actions/checkout@main
      - uses: TinycellCorp/Actions/.github/actions/setup-unity@main
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
