name: Platforms

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: 
      - self-hosted
      - macOS
    steps:
      - uses: TinycellCorp/Actions/.github/actions/checkout@main
      - uses: TinycellCorp/Actions/.github/actions/setup-unity@main
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
      - run: git restore . && git clean -df
      - uses: siren403/unity-builder@custom
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android

